from gtran.gtran import Gtran
tran = Gtran()

defaults = {
	"% 1 $ a": "%1$a",
	"% 2 $ a": "%2$a",
	"% 3 $ a": "%3$a",
	"% 4 $ a": "%4$a",
	"% 5 $ a": "%5$a",
	"% 6 $ a": "%6$a",
	"% 7 $ a": "%7$a",
	"% 8 $ a": "%8$a",
	"% 9 $ a": "%9$a",
	"% 1 $ b": "%1$b",
	"% 2 $ b": "%2$b",
	"% 3 $ b": "%3$b",
	"% 4 $ b": "%4$b",
	"% 5 $ b": "%5$b",
	"% 6 $ b": "%6$b",
	"% 7 $ b": "%7$b",
	"% 8 $ b": "%8$b",
	"% 9 $ b": "%9$b",
	"% 1 $ c": "%1$c",
	"% 2 $ c": "%2$c",
	"% 3 $ c": "%3$c",
	"% 4 $ c": "%4$c",
	"% 5 $ c": "%5$c",
	"% 6 $ c": "%6$c",
	"% 7 $ c": "%7$c",
	"% 8 $ c": "%8$c",
	"% 9 $ c": "%9$c",
	"% 1 $ d": "%1$d",
	"% 2 $ d": "%2$d",
	"% 3 $ d": "%3$d",
	"% 4 $ d": "%4$d",
	"% 5 $ d": "%5$d",
	"% 6 $ d": "%6$d",
	"% 7 $ d": "%7$d",
	"% 8 $ d": "%8$d",
	"% 9 $ d": "%9$d",
	"% 1 $ e": "%1$e",
	"% 2 $ e": "%2$e",
	"% 3 $ e": "%3$e",
	"% 4 $ e": "%4$e",
	"% 5 $ e": "%5$e",
	"% 6 $ e": "%6$e",
	"% 7 $ e": "%7$e",
	"% 8 $ e": "%8$e",
	"% 9 $ e": "%9$e",
	"% 1 $ f": "%1$f",
	"% 2 $ f": "%2$f",
	"% 3 $ f": "%3$f",
	"% 4 $ f": "%4$f",
	"% 5 $ f": "%5$f",
	"% 6 $ f": "%6$f",
	"% 7 $ f": "%7$f",
	"% 8 $ f": "%8$f",
	"% 9 $ f": "%9$f",
	"% 1 $ g": "%1$g",
	"% 2 $ g": "%2$g",
	"% 3 $ g": "%3$g",
	"% 4 $ g": "%4$g",
	"% 5 $ g": "%5$g",
	"% 6 $ g": "%6$g",
	"% 7 $ g": "%7$g",
	"% 8 $ g": "%8$g",
	"% 9 $ g": "%9$g",
	"% 1 $ h": "%1$h",
	"% 2 $ h": "%2$h",
	"% 3 $ h": "%3$h",
	"% 4 $ h": "%4$h",
	"% 5 $ h": "%5$h",
	"% 6 $ h": "%6$h",
	"% 7 $ h": "%7$h",
	"% 8 $ h": "%8$h",
	"% 9 $ h": "%9$h",
	"% 1 $ i": "%1$i",
	"% 2 $ i": "%2$i",
	"% 3 $ i": "%3$i",
	"% 4 $ i": "%4$i",
	"% 5 $ i": "%5$i",
	"% 6 $ i": "%6$i",
	"% 7 $ i": "%7$i",
	"% 8 $ i": "%8$i",
	"% 9 $ i": "%9$i",
	"% 1 $ j": "%1$j",
	"% 2 $ j": "%2$j",
	"% 3 $ j": "%3$j",
	"% 4 $ j": "%4$j",
	"% 5 $ j": "%5$j",
	"% 6 $ j": "%6$j",
	"% 7 $ j": "%7$j",
	"% 8 $ j": "%8$j",
	"% 9 $ j": "%9$j",
	"% 1 $ k": "%1$k",
	"% 2 $ k": "%2$k",
	"% 3 $ k": "%3$k",
	"% 4 $ k": "%4$k",
	"% 5 $ k": "%5$k",
	"% 6 $ k": "%6$k",
	"% 7 $ k": "%7$k",
	"% 8 $ k": "%8$k",
	"% 9 $ k": "%9$k",
	"% 1 $ l": "%1$l",
	"% 2 $ l": "%2$l",
	"% 3 $ l": "%3$l",
	"% 4 $ l": "%4$l",
	"% 5 $ l": "%5$l",
	"% 6 $ l": "%6$l",
	"% 7 $ l": "%7$l",
	"% 8 $ l": "%8$l",
	"% 9 $ l": "%9$l",
	"% 1 $ m": "%1$m",
	"% 2 $ m": "%2$m",
	"% 3 $ m": "%3$m",
	"% 4 $ m": "%4$m",
	"% 5 $ m": "%5$m",
	"% 6 $ m": "%6$m",
	"% 7 $ m": "%7$m",
	"% 8 $ m": "%8$m",
	"% 9 $ m": "%9$m",
	"% 1 $ n": "%1$n",
	"% 2 $ n": "%2$n",
	"% 3 $ n": "%3$n",
	"% 4 $ n": "%4$n",
	"% 5 $ n": "%5$n",
	"% 6 $ n": "%6$n",
	"% 7 $ n": "%7$n",
	"% 8 $ n": "%8$n",
	"% 9 $ n": "%9$n",
	"% 1 $ o": "%1$o",
	"% 2 $ o": "%2$o",
	"% 3 $ o": "%3$o",
	"% 4 $ o": "%4$o",
	"% 5 $ o": "%5$o",
	"% 6 $ o": "%6$o",
	"% 7 $ o": "%7$o",
	"% 8 $ o": "%8$o",
	"% 9 $ o": "%9$o",
	"% 1 $ q": "%1$q",
	"% 2 $ q": "%2$q",
	"% 3 $ q": "%3$q",
	"% 4 $ q": "%4$q",
	"% 5 $ q": "%5$q",
	"% 6 $ q": "%6$q",
	"% 7 $ q": "%7$q",
	"% 8 $ q": "%8$q",
	"% 9 $ q": "%9$q",
	"% 1 $ p": "%1$p",
	"% 2 $ p": "%2$p",
	"% 3 $ p": "%3$p",
	"% 4 $ p": "%4$p",
	"% 5 $ p": "%5$p",
	"% 6 $ p": "%6$p",
	"% 7 $ p": "%7$p",
	"% 8 $ p": "%8$p",
	"% 9 $ p": "%9$p",
	"% 1 $ r": "%1$r",
	"% 2 $ r": "%2$r",
	"% 3 $ r": "%3$r",
	"% 4 $ r": "%4$r",
	"% 5 $ r": "%5$r",
	"% 6 $ r": "%6$r",
	"% 7 $ r": "%7$r",
	"% 8 $ r": "%8$r",
	"% 9 $ r": "%9$r",
	"% 1 $ s": "%1$s",
	"% 2 $ s": "%2$s",
	"% 3 $ s": "%3$s",
	"% 4 $ s": "%4$s",
	"% 5 $ s": "%5$s",
	"% 6 $ s": "%6$s",
	"% 7 $ s": "%7$s",
	"% 8 $ s": "%8$s",
	"% 9 $ s": "%9$s",
	"% 1 $ t": "%1$t",
	"% 2 $ t": "%2$t",
	"% 3 $ t": "%3$t",
	"% 4 $ t": "%4$t",
	"% 5 $ t": "%5$t",
	"% 6 $ t": "%6$t",
	"% 7 $ t": "%7$t",
	"% 8 $ t": "%8$t",
	"% 9 $ t": "%9$t",
	"% 1 $ u": "%1$u",
	"% 2 $ u": "%2$u",
	"% 3 $ u": "%3$u",
	"% 4 $ u": "%4$u",
	"% 5 $ u": "%5$u",
	"% 6 $ u": "%6$u",
	"% 7 $ u": "%7$u",
	"% 8 $ u": "%8$u",
	"% 9 $ u": "%9$u",
	"% 1 $ v": "%1$v",
	"% 2 $ v": "%2$v",
	"% 3 $ v": "%3$v",
	"% 4 $ v": "%4$v",
	"% 5 $ v": "%5$v",
	"% 6 $ v": "%6$v",
	"% 7 $ v": "%7$v",
	"% 8 $ v": "%8$v",
	"% 9 $ v": "%9$v",
	"% 1 $ y": "%1$y",
	"% 2 $ y": "%2$y",
	"% 3 $ y": "%3$y",
	"% 4 $ y": "%4$y",
	"% 5 $ y": "%5$y",
	"% 6 $ y": "%6$y",
	"% 7 $ y": "%7$y",
	"% 8 $ y": "%8$y",
	"% 9 $ y": "%9$y",
	"% 1 $ z": "%1$z",
	"% 2 $ z": "%2$z",
	"% 3 $ z": "%3$z",
	"% 4 $ z": "%4$z",
	"% 5 $ z": "%5$z",
	"% 6 $ z": "%6$z",
	"% 7 $ z": "%7$z",
	"% 8 $ z": "%8$z",
	"% 9 $ z": "%9$z",
	"% a": "%a",
	"% b": "%b",
	"% c": "%c",
	"% d": "%d",
	"% e": "%e",
	"% f": "%f",
	"% g": "%g",
	"% h": "%h",
	"% i": "%i",
	"% j": "%j",
	"% k": "%k",
	"% l": "%l",
	"% m": "%m",
	"% n": "%n",
	"% o": "%o",
	"% q": "%q",
	"% p": "%p",
	"% r": "%r",
	"% s": "%s",
	"% t": "%t",
	"% u": "%u",
	"% v": "%v",
	"% y": "%y",
	"% z": "%z",
	"% 1": "%1",
	"% 2": "%2",
	"% 3": "%3",
	"% 4": "%4",
	"% 5": "%5",
	"% 6": "%6",
	"% 7": "%7",
	"% 8": "%8",
	"% 9": "%9",
	"End City": "Thành phố kết thúc",
	"Nether Fortress": "Pháo đài địa ngục",
	"Woodland Mansion": "Biệt thự trong rừng",
	"Mineshaft": "Khu mỏ",
	"Unknown Feature": "Tính năng không rõ",
	"Ocean Monument": "Đài tưởng niệm đại dương",
	"Stronghold": "Thành trì",
	"Temple": "Ngôi đèn",
	"Village": "Làng mạc",
	"Shipwreck": "Tàu đắm",
	"Buried Treasure": "Kho báu bị trôn đi",
	"Ocean Ruins": "Di tích đại dương cổ",
	"Pillager Outpost": "Trụ sở ác dân",
	"Bastion Remnant": "Căn cứ tàn dư",
	"Ruined Portal": "Cổng địa ngục bị phá hủy",
	"Wi-Fi": "Wifi",
	"Mesa": "Đồi núi hoang vu",
	"Nether": "Địa ngục",
}
def fix(string):
	for i, v in defaults.items():
		string = string.replace(i, v)
	return string
def addLine(str $lfile_name, str line):
	file = open(filename, "a")
	file.write(line)
	file.close()
sources = dict()
out = open("out.lang", "tw+")
with open("vi_VN.lang") as lines:
	for line in lines:
		epos = line.find("=")
		xpos = line.find("##")
		if epos > 0:
			key = line[:epos]
			if not key[0].isalpha():
				key = key[1:]
			if xpos > 0:
				val = fix(line[epos+1:].rstrip(line[xpos:]))
			else:
				val = fix(line[epos+1:].rstrip("\n"))
			sources[key] = val
with open("en_US.lang") as lines:
	for line in lines:
		epos = line.find("=")
		xpos = line.find("##")
		if epos > 0:
			key = line[:epos].replace(" ", "")
			if not key[0].isalpha():
				key = key[1:]
			if xpos > 0:
				val = line[epos+1:].rstrip(line[xpos:])
			else:
				val = line[epos+1:].rstrip("\n")
			if key in sources.keys():
				val = sources[key]
			else:
				val = fix(tran.translate(to_lang="vi", text=val)) + eol
				addLine("trans.lang", key + "=" + val + "\n")
				print("Trans: " + key + "=" + val)
			addLine("out.lang", key + "=" + val + "\n") 